package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javafx.event.ActionEvent;

public class LoginController {
	@FXML
	private TextField username;
	@FXML
	private TextField password;
	@FXML
	private Button loginBtn;
	@FXML
	private Button newEmpBtn;
	
	//	DATABASE TOOLS
	private Connection connect;
	private PreparedStatement prepare;
	private ResultSet result;
	
	public void loginAdmin(ActionEvent event) {
		String sql = "SELECT * FROM login_info WHERE username = ? and password = ?";
		
		connect = database.connectDb("empdb");
		
		try {
			prepare = connect.prepareStatement(sql);
			prepare.setString(1, username.getText());
			prepare.setString(2, password.getText());
			
			result = prepare.executeQuery();
			Alert alert;
						
			if(username.getText().isEmpty() || password.getText().isEmpty()) {
				alert = new Alert(AlertType.ERROR);
				alert.setTitle("Error Message");
				alert.setHeaderText(null);
				alert.setContentText("Enter all blank fields");
				alert.show();
			}else {
				if(result.next()) {					
					loginBtn.getScene().getWindow().hide();
					Parent root = FXMLLoader.load(getClass().getResource("EffortConsole.fxml"));
					Stage stage = new Stage();
					Scene scene = new Scene(root);
					
					stage.setScene(scene);
					stage.show();
					
				}else {
					alert = new Alert(AlertType.ERROR);
					alert.setTitle("Error Message");
					alert.setHeaderText(null);
					alert.setContentText("Wrong Username/Password");
					alert.show();
				}
			}
		}catch(Exception e) {e.printStackTrace();}
		finally{
    		if (result != null) {
    	        try {
    	            result.close();
    	        } catch (SQLException e) {e.addSuppressed(null);}
    	    }
    	    if (prepare != null) {
    	        try {
    	            prepare.close();
    	        } catch (SQLException e) { e.addSuppressed(null);}
    	    }
    	    if (connect != null) {
    	        try {
    	            connect.close();
    	        } catch (SQLException e) { e.addSuppressed(null);}
    	    }
    	}
	}

	public void newEmp (ActionEvent event) {
		// TODO Autogenerated
		try {
    		newEmpBtn.getScene().getWindow().hide();
			Parent root = FXMLLoader.load(getClass().getResource("AccountCreation.fxml"));
			Stage stage = new Stage();
			Scene scene = new Scene(root);
			
			stage.setScene(scene);
			stage.show();
    	}catch(Exception e) {e.printStackTrace();}
	}
	
	
		
}
